// <auto-generated />
using System;
using DiveLogg.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiveLogg.Migrations
{
    [DbContext(typeof(DiveLoggContext))]
    [Migration("20260218134131_FixPersonGroupRequired")]
    partial class FixPersonGroupRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("DiveLogg.Models.Dive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiveLeaderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiveTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExposureTime")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("LocationName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("NitrogenLoad")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiveLeaderId");

                    b.ToTable("Dive");
                });

            modelBuilder.Entity("DiveLogg.Models.DiveParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiveId");

                    b.HasIndex("PersonId");

                    b.HasIndex("RoleId");

                    b.ToTable("DiveParticipant");
                });

            modelBuilder.Entity("DiveLogg.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Group");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Grupp 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Grupp 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Grupp 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Grupp 4"
                        });
                });

            modelBuilder.Entity("DiveLogg.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("DiveLogg.Models.PersonRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("PersonId", "RoleId")
                        .IsUnique();

                    b.ToTable("PersonRole");
                });

            modelBuilder.Entity("DiveLogg.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Diver"
                        },
                        new
                        {
                            Id = 2,
                            Name = "DiveLeader"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DiveSupport"
                        });
                });

            modelBuilder.Entity("DiveLogg.Models.Dive", b =>
                {
                    b.HasOne("DiveLogg.Models.Person", "DiveLeader")
                        .WithMany("LedDives")
                        .HasForeignKey("DiveLeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DiveLeader");
                });

            modelBuilder.Entity("DiveLogg.Models.DiveParticipant", b =>
                {
                    b.HasOne("DiveLogg.Models.Dive", "Dive")
                        .WithMany("DiveParticipants")
                        .HasForeignKey("DiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiveLogg.Models.Person", "Person")
                        .WithMany("DiveParticipants")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiveLogg.Models.Role", "Role")
                        .WithMany("DiveParticipants")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dive");

                    b.Navigation("Person");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DiveLogg.Models.Person", b =>
                {
                    b.HasOne("DiveLogg.Models.Group", "Group")
                        .WithMany("Persons")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("DiveLogg.Models.PersonRole", b =>
                {
                    b.HasOne("DiveLogg.Models.Person", "Person")
                        .WithMany("PersonRoles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiveLogg.Models.Role", "Role")
                        .WithMany("PersonRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DiveLogg.Models.Dive", b =>
                {
                    b.Navigation("DiveParticipants");
                });

            modelBuilder.Entity("DiveLogg.Models.Group", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("DiveLogg.Models.Person", b =>
                {
                    b.Navigation("DiveParticipants");

                    b.Navigation("LedDives");

                    b.Navigation("PersonRoles");
                });

            modelBuilder.Entity("DiveLogg.Models.Role", b =>
                {
                    b.Navigation("DiveParticipants");

                    b.Navigation("PersonRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
